In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import chardet#for encoding
import warnings# to avoid the warnings
warnings.filterwarnings('ignore')
pd.pandas.set_option('display.max_columns',0)

In [2]:
data=pd.read_csv("After_EDA.csv",index_col=0)
data.head()

          Lng        Lat  tradeTime  ...  floor_type_未知  floor_type_顶  floor_type_高
0  116.475489  40.019520       2016  ...          False         False          True
1  116.453917  39.881534       2016  ...          False         False          True
2  116.561978  39.877145       2016  ...          False         False         False
3  116.438010  40.076114       2016  ...          False         False         False
4  116.428392  39.886229       2016  ...          False         False         False

[5 rows x 45 columns]

### Let's Findout the outlier in a dataset using Inter quartile Range(IQR)

In [3]:
data['totalPrice'].describe()

count    297990.000000
mean        349.178136
std         224.530679
min           0.100000
25%         205.000000
50%         295.000000
75%         427.000000
max        4900.000000
Name: totalPrice, dtype: float64

In [4]:
data.totalPrice.quantile([0.25,0.50,0.75])

0.25    205.0
0.50    295.0
0.75    427.0
Name: totalPrice, dtype: float64

so,we got 

Q1=205 and
Q3=427

so,let's findout IQR

In [5]:
Q1=205
Q3=427
IQR=Q3-Q1
print("So,IQR of our totalPrice Features is",IQR)

So,IQR of our totalPrice Features is 222

In [6]:
#Let's Calculate the High and Low Value in a totalPrice Features
High=Q3+1.5*IQR
Low=Q1-1.5*IQR
print("High value of our totalPrice Features is",High)
print("Low value of our totalPrice Features is",Low)

High value of our totalPrice Features is 760.0
Low value of our totalPrice Features is -128.0

In [7]:
df=data.copy()

In [8]:
#Let's remove the outlier
df=df[df['totalPrice']<=High]
df=df[df['totalPrice']>=Low]

In [9]:
print(data.shape)
print(df.shape)

(297990, 45)
(283869, 45)

In [10]:
print("Total outlier Removed =",data.shape[0]-df.shape[0])

Total outlier Removed = 14121

#### Let's Findout important features for out model

In [11]:
df.columns

Index(['Lng', 'Lat', 'tradeTime', 'followers', 'totalPrice', 'square',
       'livingRoom', 'drawingRoom', 'kitchen', 'bathRoom', 'constructionTime',
       'ladderRatio', 'fiveYearsProperty', 'subway', 'communityAverage',
       'floor_height', 'renovationCondition_2', 'renovationCondition_3',
       'renovationCondition_4', 'buildingStructure_2', 'buildingStructure_3',
       'buildingStructure_4', 'buildingStructure_5', 'buildingStructure_6',
       'buildingType_2.0', 'buildingType_3.0', 'buildingType_4.0',
       'district_2', 'district_3', 'district_4', 'district_5', 'district_6',
       'district_7', 'district_8', 'district_9', 'district_10', 'district_11',
       'district_12', 'district_13', 'elevator_1.0', 'floor_type_低',
       'floor_type_底', 'floor_type_未知', 'floor_type_顶', 'floor_type_高'],
      dtype='object')

In [12]:
X=df.drop(['totalPrice'],axis=1)
y=df['totalPrice']

In [13]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /Users/bhawnagarg/Library/Python/3.8/lib/python/site-packages (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/bhawnagarg/Library/Python/3.8/lib/python/site-packages (from scikit-learn) (3.2.0)
Requirement already satisfied: scipy>=1.5.0 in /Users/bhawnagarg/Library/Python/3.8/lib/python/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /Users/bhawnagarg/Library/Python/3.8/lib/python/site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: joblib>=1.1.1 in /Users/bhawnagarg/Library/Python/3.8/lib/python/site-packages (from scikit-learn) (1.3.2)

[notice] A new release of pip available: 22.3 -> 23.3.1
[notice] To update, run: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Data Normalization
Normalization (min-max Normalization)

In this approach we scale down the feature in  between 0 to 1

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaling=MinMaxScaler()

In [16]:
col_for_normalization=['Lng', 'Lat','followers','square','livingRoom', 'drawingRoom',
                       'kitchen', 'bathRoom','ladderRatio', 'fiveYearsProperty', 
                       'subway', 'communityAverage','floor_height']

In [17]:
df[col_for_normalization]=scaling.fit_transform(df[col_for_normalization])

In [18]:
df.head()

        Lng       Lat  tradeTime  ...  floor_type_未知  floor_type_顶  floor_type_高
0  0.630809  0.627253       2016  ...          False         False          True
1  0.597040  0.406733       2016  ...          False         False          True
3  0.572140  0.717698       2016  ...          False         False         False
4  0.557084  0.414236       2016  ...          False         False         False
5  0.616393  0.582255       2016  ...          False         False         False

[5 rows x 45 columns]

In [19]:
df.to_csv("Data_For_Model.csv")